### ISSUE TITLE
Add values to response?

### ISSUE THREAD

**Issue by fabiosoft** [XVincentX/express-gateway-plugin-body-modifier#1]
Can i access to response for adding a parameter?

The following yml config does nothing :(  (i think it crashed internally, but no logs are showed)

```
    policies:
      - body-modifier:
          action:
            request:
              add:
              - name: fullname
                value: req.body.name
            response:
              add:
              - name: ip
                value: res.body.url
              remove:
              - origin
```
